version: "3.7"
services:
  db:
    image: mysql:8.0.31
    # authentication-policy is the latest option
    command: '--authentication-policy=mysql_native_password'
    restart: always
    secrets:
      - db-password
    environment:
      MYSQL_DATABASE: example
      # NOT FOR PROD. This is just a quick way to inject credential.
      # MYSQL_ROOT_PASSWORD was used in earlier versions.
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network
  api:
    build: app
    restart: always
    secrets:
      - db-password
    networks:
      - frontend-network
      - backend-network
  web:
    build: web
    restart: always
    ports:
      - 8880:80
    networks:
      - frontend-network
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  frontend-network:
  backend-network:
